version: "1.0"
info:
  model: int-scaffold
packages:
- name: RajniTest190126Project
  gitServerName: KusiVCAccount
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: KusiVCAccount
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: KusiVCAccount
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Rajni25Aug
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: KusiVCAccount
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Rajni25Aug
  gitBranch: gv25var
- name: SIQA_TimeoutTest
  version: "1.0"
  gitServerName: KusiVCAccount
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Rajni25Aug
  gitBranch: main
- name: WmSalesforceRESTProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.rajnitest190126.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:tesAlias
  packages:
  - name: RajniTest190126Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQA_TimeoutTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.rajnitest190126.integrations:Alert
  packages:
  - name: RajniTest190126Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQA_TimeoutTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: project.rajnitest190126.integrations:Sum
  packages:
  - name: RajniTest190126Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQA_TimeoutTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: project.rajnitest190126.integrations:deepclonetest
  packages:
  - name: RajniTest190126Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQA_TimeoutTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: project.rajnitest190126.integrations:testGVConn
  packages:
  - name: RajniTest190126Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQA_TimeoutTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: GB_1:readGlobalvariable
  packages:
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 12.0.0.0.698
- serviceName: SIQACloudStreamsTests:connetorOperations
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
- serviceName: SIQACloudStreamsTests:createAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
- serviceName: SIQACloudStreamsTests:retrieveAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
- serviceName: SIQACloudStreamsTests:deleteAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
- serviceName: SIQAJDBCAdapterTests.adapterServices:getData
  packages:
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  jdbc.Embedded-Database-Pool.waitingThread: "0"
  jdbcfunc.ISDashboardStats.failFastMode: false
  jdbc.Embedded-Database-Pool.spyenabled: "false"
  jdbcfunc.Xref.failFastMode: true
  jdbcfunc.ISDashboardStats.connPoolAlias: Embedded-Database-Pool
  jdbcfunc.Xref.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.userid: APP
  jdbcfunc.ISInternal.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.password: "{AES}Zcw2EXTJgNDVmVzJO2Y3Bw=="
  jdbc.Embedded-Database-Pool.snoopenabled: "false"
  jdbcfunc.ISInternal.failFastMode: true
  jdbc.Embedded-Database-Pool.maxConns: "10"
  jdbc.Embedded-Database-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.poolThreshold: "0"
  jdbc.Embedded-Database-Pool.useSSL: "false"
  jdbc.Embedded-Database-Pool.minConns: "0"
  jdbc.Embedded-Database-Pool.driverAlias: Embedded Database Driver
  jdbc.Embedded-Database-Pool.dbURL: jdbc:derby:embedded;create=true
